---
- name: Install Checkmk agent 
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Download Checkmk Agent
      get_url:
        url: https://download.checkmk.com/checkmk/2.1.0p19/check-mk-free-2.1.0p19-el8-38.x86_64.rpm
        dest: /tmp/check-mk-agent.rpm
    - name: Install Checkmk Agent
      package:
        name: /tmp/check-mk-agent.rpm
        state: present
    - name: Start and enable Checkmk Agent service
      service:
        name: check-mk-agent
        enabled: true
        state: started
    - name: Install xinetd package
      package:
        name: xinetd
        state: present
    - name: Start and enable xinetd service
      service:
        name: xinetd
        state: started
        enabled: true
    - name: Add check-mk-access line
      lineinfile:
        path: /etc/xinetd.d/check-mk-agent
        line: '        only_from      = 127.0.0.1 137.108.216.32/27 137.108.216.64/26 10.10.8.15'
        state: present
        regexp: '(.*)only_from(.*)'
    - name: Add firewall rule for check-mk-agent
      firewalld:
        zone: public
        service: check-mk-agent
        state: enabled
        permanent: true
      when: lsbmajdistrelease >= '7'
    - name: Add firewall rich rule for monitoring subnet
      firewalld:
        zone: public
        source: "{{ item }}"
        family: ipv4
        rule: "rule family='ipv4' source address='{{ item }}' accept"
        state: enabled
        permanent: true
        element: service
        servicename: check-mk-agent
      when: lsbmajdistrelease >= '7'
      loop: ["137.108.216.32/27", "137.108.216.64/26", "10.10.8.15"]
